version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: always
    env_file:
      - mySQL.env
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - challengeApp.env
    depends_on:
      - mysql
      - redis
    
volumes:
  mysql-data:
  redis-data: